export const listBusiness = [
    {
        "id_empresa": 1,
        "nome": "John's Company",
        "email": "johnscompany@example.com",
        "senha": "passwordA",
        "CNPJ": "12345678900001",
        "site": "http://www.johnscompany.com",
        "descricao": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eros urna, maximus id nulla ultricies, dictum pulvinar justo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse feugiat porta imperdiet. Sed nunc diam, vestibulum at porta id, congue vel dui. Curabitur ac gravida arcu. Suspendisse consequat ornare erat, ac auctor leo elementum non. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. ",
        "categoria": "Tecnologia",
        "media": 8.5,
    },
    {
        "id_empresa": 2,
        "nome": "Smith Enterprises",
        "email": "smithenterprises@example.com",
        "senha": "passwordB",
        "CNPJ": "12345678900002",
        "site": "http://www.smithenterprises.com",
        "descricao": "Uma empresa inovadora dedicada a fornecer serviços excepcionais.",
        "categoria": "Consultoria",
        "media": 7.2,
    },
    {
        "id_empresa": 3,
        "nome": "Anderson Corp",
        "email": "andersoncorp@example.com",
        "senha": "passwordC",
        "CNPJ": "12345678900003",
        "site": "http://www.andersoncorp.com",
        "descricao": "Uma corporação comprometida com a excelência em seus produtos e serviços.",
        "categoria": "Tecnologia",
        "media": 9.0,
    },
    {
        "id_empresa": 4,
        "nome": "Robinson Ltd",
        "email": "robinsonltd@example.com",
        "senha": "passwordD",
        "CNPJ": "12345678900004",
        "site": "http://www.robinsonltd.com",
        "descricao": "Uma empresa global que se destaca na entrega de soluções abrangentes.",
        "categoria": "Logística",
        "media": 8.7,
    },
    {
        "id_empresa": 5,
        "nome": "Taylor & Sons",
        "email": "taylorandsons@example.com",
        "senha": "passwordE",
        "CNPJ": "12345678900005",
        "site": "http://www.taylorandsons.com",
        "descricao": "Uma empresa familiar dedicada à qualidade e satisfação do cliente.",
        "categoria": "Consultoria",
        "media": 3,
    },
    {
        "id_empresa": 6,
        "nome": "Green Solutions Ltd",
        "email": "greensolutions@example.com",
        "senha": "passwordF",
        "CNPJ": "12345678900006",
        "site": "http://www.greensolutions.com",
        "descricao": "Uma empresa comprometida com soluções ecológicas e sustentáveis.",
        "categoria": "Meio Ambiente",
        "media": 8.3,
    },
    {
        "id_empresa": 7,
        "nome": "InovaTech Solutions",
        "email": "innovatech@example.com",
        "senha": "passwordG",
        "CNPJ": "12345678900007",
        "site": "http://www.innovatechsolutions.com",
        "descricao": "Líder em inovação e tecnologia, fornecendo soluções avançadas para clientes globais.",
        "categoria": "Tecnologia",
        "media": 9.5,
    },
    {
        "id_empresa": 8,
        "nome": "Global Logistics Inc",
        "email": "globallogistics@example.com",
        "senha": "passwordH",
        "CNPJ": "12345678900008",
        "site": "http://www.globallogistics.com",
        "descricao": "Especialistas em logística global, conectando o mundo com eficiência.",
        "categoria": "Logística",
        "media": 8.0,
    },
    {
        "id_empresa": 9,
        "nome": "Nature's Bounty Co.",
        "email": "naturesbounty@example.com",
        "senha": "passwordI",
        "CNPJ": "12345678900009",
        "site": "http://www.naturesbounty.com",
        "descricao": "Dedicados a oferecer produtos naturais e saudáveis para uma vida melhor.",
        "categoria": "Saúde",
        "media": 9.2,
    },
    {
        "id_empresa": 10,
        "nome": "Digital Innovations Ltd",
        "email": "digitalinnovations@example.com",
        "senha": "passwordJ",
        "CNPJ": "12345678900010",
        "site": "http://www.digitalinnovations.com",
        "descricao": "Impulsionando a inovação digital com soluções avançadas e personalizadas.",
        "categoria": "Tecnologia",
        "media": 8.8,
    },
    {
        "id_empresa": 11,
        "nome": "LowRate Solutions",
        "email": "lowrate@example.com",
        "senha": "passwordK",
        "CNPJ": "12345678900011",
        "site": "http://www.lowrate.com",
        "descricao": "Oferecendo soluções acessíveis para clientes com orçamentos limitados.",
        "categoria": "Serviços Gerais",
        "media": 4.2,
    },
    {
        "id_empresa": 12,
        "nome": "BudgetTech Co.",
        "email": "budgettech@example.com",
        "senha": "passwordL",
        "CNPJ": "12345678900012",
        "site": "http://www.budgettech.com",
        "descricao": "Fornecendo tecnologia a preços acessíveis para pequenas empresas.",
        "categoria": "Tecnologia",
        "media": 3.8,
    },
    {
        "id_empresa": 13,
        "nome": "EconoGoods Ltd",
        "email": "econogoods@example.com",
        "senha": "passwordM",
        "CNPJ": "12345678900013",
        "site": "http://www.econogoods.com",
        "descricao": "Produtos e serviços econômicos para clientes conscientes dos custos.",
        "categoria": "Varejo",
        "media": 4.6,
    },
    {
        "id_empresa": 14,
        "nome": "Embraer",
        "email": "embraer@example.com",
        "senha": "passwordM",
        "CNPJ": "12345678900013",
        "site": "http://www.econogoods.com",
        "descricao": "Produtos e serviços econômicos para clientes conscientes dos custos.",
        "categoria": "Varejo",
        "media": 5.3,
    },
];