
export const complaints = [
    {
        id: 1,
        id_empresa: 1,
        id_consumidor: 101,
        categoria_reclamacao: 'Produto',
        id_pai: null,
        titulo: 'Problema com entrega',
        descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eros urna, maximus id nulla ultricies, dictum pulvinar justo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse feugiat porta imperdiet. Sed nunc diam, vestibulum at porta id, congue vel dui. Curabitur ac gravida arcu. Suspendisse consequat ornare erat, ac auctor leo elementum non. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. ",
        bo_ativado: true,
        status: 'Aguardando',
        data: '2024-01-24'
    },
    {
        id: 2,
        id_empresa: 2,
        id_consumidor: 102,
        categoria_reclamacao: 'Atendimento',
        id_pai: null,
        titulo: 'Produto danificado',
        descricao: 'O produto chegou danificado, preciso de uma solução.',
        bo_ativado: true,
        status: 'Não Respondida',
        data: '2024-01-23'
    },
    {
        id: 3,
        id_empresa: 3,
        id_consumidor: 103,
        categoria_reclamacao: 'Serviço',
        id_pai: null,
        titulo: 'Serviço não realizado',
        descricao: 'Contratei um serviço que não foi realizado conforme acordado.',
        bo_ativado: true,
        status: 'Respondida',
        data: '2024-01-22'
    },
    {
        id: 4,
        id_empresa: 4,
        id_consumidor: 104,
        categoria_reclamacao: 'Produto',
        id_pai: null,
        titulo: 'Prazo de entrega não cumprido',
        descricao: 'O prazo de entrega do produto não foi cumprido.',
        bo_ativado: true,
        status: 'Não Respondida',
        data: '2024-01-21'
    },
    {
        id: 5,
        id_empresa: 5,
        id_consumidor: 105,
        categoria_reclamacao: 'Atendimento',
        id_pai: null,
        titulo: 'Falta de suporte técnico',
        descricao: 'Não consigo obter suporte técnico para meu produto.',
        bo_ativado: true,
        status: 'Aguardando',
        data: '2024-01-20'
    },
    {
        id: 6,
        id_empresa: 6,
        id_consumidor: 106,
        categoria_reclamacao: 'Serviço',
        id_pai: null,
        titulo: 'Cobrança indevida',
        descricao: 'Fui cobrado indevidamente por um serviço não contratado.',
        bo_ativado: true,
        status: 'Não Respondida',
        data: '2024-01-19'
    },
    {
        id: 7,
        id_empresa: 7,
        id_consumidor: 107,
        categoria_reclamacao: 'Produto',
        id_pai: null,
        titulo: 'Produto com defeito',
        descricao: 'O produto recebido está com defeito, quero um reembolso.',
        bo_ativado: true,
        status: 'Respondida',
        data: '2024-01-18'
    },
    {
        id: 8,
        id_empresa: 8,
        id_consumidor: 108,
        categoria_reclamacao: 'Atendimento',
        id_pai: null,
        titulo: 'Demora no atendimento telefônico',
        descricao: 'Estou esperando muito tempo para ser atendido pelo telefone.',
        bo_ativado: true,
        status: 'Aguardando',
        data: '2024-01-17'
    },
    {
        id: 9,
        id_empresa: 9,
        id_consumidor: 109,
        categoria_reclamacao: 'Serviço',
        id_pai: null,
        titulo: 'Problema com instalação',
        descricao: 'Não consigo instalar o software corretamente.',
        bo_ativado: true,
        status: 'Não Respondida',
        data: '2024-01-16'
    },
    {
        id: 10,
        id_empresa: 10,
        id_consumidor: 110,
        categoria_reclamacao: 'Produto',
        id_pai: null,
        titulo: 'Produto com defeito',
        descricao: 'Recebi o produto com defeito, quero uma solução.',
        bo_ativado: true,
        status: 'Aguardando',
        data: '2024-01-15'
    },
    {
        id: 12,
        id_empresa: 1,
        id_consumidor: 22,
        categoria_reclamacao: 'Produto',
        id_pai: null,
        titulo: 'Produto com defeito',
        descricao: 'Recebi o produto com defeito, quero uma solução.',
        bo_ativado: true,
        status: 'Aguardando',
        data: '2024-01-15'
    },
    {
        id: 13,
        id_empresa: 1,
        id_consumidor: 22,
        categoria_reclamacao: 'Produto',
        id_pai: null,
        titulo: 'Produto com defeito',
        descricao: 'Recebi o produto com defeito, quero uma solução.',
        bo_ativado: true,
        status: 'Não Respondida',
        data: '2024-01-15'
    },
    {
        id: 14,
        id_empresa: 1,
        id_consumidor: 22,
        categoria_reclamacao: 'Produto',
        id_pai: null,
        titulo: 'Produto com defeito',
        descricao: 'Recebi o produto com defeito, quero uma solução.',
        bo_ativado: true,
        status: 'Aguardando',
        data: '2024-01-15'
    },
    {
        id: 15,
        id_empresa: 1,
        id_consumidor: 22,
        categoria_reclamacao: 'Produto',
        id_pai: null,
        titulo: 'Produto com defeito',
        descricao: 'Recebi o produto com defeito, quero uma solução.',
        bo_ativado: true,
        status: 'Aguardando',
        data: '2024-01-15'
    },
    {
        id: 16,
        id_empresa: 1,
        id_consumidor: 22,
        categoria_reclamacao: 'Serviço',
        id_pai: null,
        titulo: 'Má qualidade',
        descricao: 'O serviço da empresa é horrivel, tudo ruim.',
        bo_ativado: true,
        status: 'Respondida',
        data: '2024-01-15'
    },
    {
        id: 17,
        id_empresa: 1,
        id_consumidor: 22,
        categoria_reclamacao: 'Produto',
        id_pai: null,
        titulo: 'Produto com defeito',
        descricao: 'Recebi o produto com defeito, quero uma solução.',
        bo_ativado: true,
        status: 'Respondida',
        data: '2024-01-15'
    },
    {
        id: 18,
        id_empresa: 1,
        id_consumidor: 22,
        categoria_reclamacao: 'Entrega',
        id_pai: null,
        titulo: 'Entrega está atrasada',
        descricao: 'Minha entrega está atrasada a um mes.',
        bo_ativado: true,
        status: 'Respondida',
        data: '2024-01-15'
    },
    {
        id: 19,
        id_empresa: 1,
        id_consumidor: 22,
        categoria_reclamacao: 'Produto',
        id_pai: null,
        titulo: 'Produto não recebido',
        descricao: 'Comprei um produto e ele não foi entregue.',
        bo_ativado: true,
        status: 'Respondida',
        data: '2024-02-21'
    },
    {
        id: 20,
        id_empresa: 1,
        id_consumidor: 22,
        categoria_reclamacao: 'Compras',
        id_pai: null,
        titulo: 'Compra indesejada',
        descricao: 'Comprei um produto por emgano e não aceitaram devolução.',
        bo_ativado: true,
        status: 'Respondida',
        data: '2024-03-01'
    },
    {
        id: 21,
        id_empresa: 1,
        id_consumidor: 22,
        categoria_reclamacao: 'Compras',
        id_pai: 1,
        titulo: 'Compra indesejada21',
        descricao: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam blandit libero in metus vehicula, eget pharetra urna ultrices. Donec dignissim ante vel augue gravida luctus. Cras venenatis ex sed ante lacinia tempus. Aliquam vitae posuere turpis. Aliquam a orci nec risus rutrum euismod. Donec risus dolor, imperdiet ut elit id, fringilla hendrerit odio. ',
        bo_ativado: true,
        status: 'Respondida',
        data: '2024-03-01'
    },
    {
        id: 22,
        id_empresa: 1,
        id_consumidor: 23,
        categoria_reclamacao: 'Problema de atendimento',
        id_pai: null,
        titulo: 'Péssimo atendimento',
        descricao: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam blandit libero in metus vehicula, eget pharetra urna ultrices. Donec dignissim ante vel augue gravida luctus. Cras venenatis ex sed ante lacinia tempus. Aliquam vitae posuere turpis. Aliquam a orci nec risus rutrum euismod. Donec risus dolor, imperdiet ut elit id, fringilla hendrerit odio. ',
        bo_ativado: true,
        status: 'Não Respondida',
        data: '2024-03-01'
    },
    {
        id: 23,
        id_empresa: 1,
        id_consumidor: 20,
        categoria_reclamacao: 'Problema Técnico',
        id_pai: 1,
        titulo: 'Aparelho queimou',
        descricao: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam blandit libero in metus vehicula, eget pharetra urna ultrices. Donec dignissim ante vel augue gravida luctus. Cras venenatis ex sed ante lacinia tempus. Aliquam vitae posuere turpis. Aliquam a orci nec risus rutrum euismod. Donec risus dolor, imperdiet ut elit id, fringilla hendrerit odio. ',
        bo_ativado: true,
        status: 'respondida',
        data: '2024-03-01'
    },
    {
        id: 24,
        id_empresa: 1,
        id_consumidor: 20,
        categoria_reclamacao: 'Problema Técnico',
        id_pai: 2,
        titulo: 'Aparelho queimou',
        descricao: 'imperdiet ut elit id, fringilla hendrerit odio. ',
        bo_ativado: true,
        status: 'respondida',
        data: '2024-03-01'
    },

];